### ISSUE TITLE
Ability to parse fields with their VRs

### ISSUE THREAD

**Issue by Arty233** [radialogica/dicom-character-set#8]
Hi! Documentation says we are able to use options object with VR field. Are we able to do more correct parse of fields with this thing?
E.g. "Adams^John Robert Quincy^^Rev.^B.A. M.Div." => "John Robert Quincy Adams, B.A. M.Div." for VR: PN as described [here](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html)

**Comment by yagni** [comment]
That would be something more suited for a parsing library like [dicomParser](https://github.com/cornerstonejs/dicomParser). This is a very low-level library that only handles converting raw bytes into a single string. Try requesting over in dicomParser.
