### ISSUE TITLE
Is multi-valued data for character sets ISO 2022 IR 13\ISO 2022 IR 87 supported?

### ISSUE THREAD

**Issue by karl-exini** [radialogica/dicom-character-set#9]
I am trying to understand if we are seeing the correct behavior with Japanese data we have received. The data contains the attribute (0010,1001) (Other Patient Names) with multi-valued entries with character sets "ISO 2022 IR 13\ISO 2022 IR 87". After decoding, the backslash symbols used to denote the multiple names is decoded as the ¥ symbol. 

Example input data: `ﾔﾏﾀﾞ\ﾀﾛｳ=山田\太郎=やまだ\たろう` (Bytes `[0xd4, 0xcf, 0xc0, 0xde, 0x5c, 0xc0, 0xdb, 0xb3, 0x3d, 0x1b, 0x24, 0x42, 0x3b, 0x33, 0x45, 0x44, 0x1b, 0x28, 0x4a, 0x5c, 0x1b, 0x24, 0x42, 0x42, 0x40, 0x4f, 0x3a, 0x1b, 0x28, 0x4a, 0x3d, 0x1b, 0x24, 0x42, 0x24, 0x64, 0x24, 0x5e, 0x24, 0x40, 0x1b, 0x28, 0x4a, 0x5c, 0x1b, 0x24, 0x42, 0x24, 0x3f, 0x24, 0x6d, 0x24, 0x26, 0x1b, 0x28, 0x4a]`)
Actual output: `ﾔﾏﾀﾞ¥ﾀﾛｳ=山田¥太郎=やまだ¥たろう`

In our DICOM library, the value is first decoded and then split on the backslash character. This obviously does not work in this instance. Are we using the library wrong or is this a bug/limitation?

**Comment by yagni** [comment]
Looks like a bug. The standard indicates that multi-valued VRs that [support alternate character sets](https://dicom.nema.org/medical/dicom/current/output/html/part03.html#sect_C.12.1.1.2) (SH, LO, PN, UC) don't allow 0x5c as a valid character (see the Character Repertoire column [here](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html)) so it doesn't make sense to convert them to the yen symbol. Expect a fix shortly.
